apiVersion: v1
kind: Pod
metadata:
  name: trouble
  namespace: testing
spec:
  serviceAccountName: service-account
  containers:
  - name: trouble
    image: g1g1/py-kube:0.3
    volumeMounts:
    - name: generic-secret
      mountPath: /etc/generic-secret
      readOnly: true
  volumes:
    - name: generic-secret
      secret:
        secretName: generic-secret
