FROM golang:alpine AS builder

WORKDIR $GOROOT/src/github.com/TaskMasterErnest/microservice-with-kubernetes/svc/link_service
COPY ./main.go main.go
COPY ./service service

RUN go mod init link_service

# Fetch dependencies
RUN go get

RUN CGO_ENABLED=0 GOOS=linux go build -o /link_service

EXPOSE 8080
ENTRYPOINT ["/link_service"]