FROM golang:1.17-alpine AS builder

WORKDIR $GOROOT/src/github.com/TaskMasterErnest/microservice-with-kubernetes/svc/social_graph_service
# Copy files
COPY ./main.go main.go
COPY ./service service
COPY go.mod go.mod
COPY go.sum go.sum

# Fetch dependencies
RUN CGO_ENABLED=0 GOOS=linux go build -o /social_graph_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/social_graph_service"]
